version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk-node

    steps:
      - checkout
      - restore_cache:
          key: v1-ttorrent-core-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn clean -Dskip.surefire.tests=false -D=skip.failsafe.tests=false verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: target/site
      - save_cache:
          key: v1-ttorrent-core-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  deploy:
    docker:
      - image: circleci/openjdk:11.0-jdk-node
    steps:
      - checkout
      - run: mvn clean package

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
